# Generated by Django 4.2.7 on 2025-12-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('natural_language_input', models.TextField(help_text='Natural language description of the RFP requirements')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget in currency', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('evaluating', 'Evaluating')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RFP',
                'verbose_name_plural': 'RFPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RFPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications or requirements for this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfp.rfp')),
            ],
            options={
                'verbose_name': 'RFP Item',
                'verbose_name_plural': 'RFP Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_email_content', models.TextField(help_text='Original email content from vendor')),
                ('extracted_price', models.DecimalField(blank=True, decimal_places=2, help_text='AI-extracted price from proposal', max_digits=12, null=True)),
                ('extracted_terms', models.TextField(blank=True, help_text='AI-extracted terms and conditions')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the proposal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='rfp.rfp')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='rfp.vendor')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
                'unique_together': {('rfp', 'vendor')},
            },
        ),
    ]
