# Generated by Django 4.2.7 on 2025-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='extracted_price',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='extracted_terms',
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Payment terms (e.g., Net 30, 50% upfront)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proposal price/quote', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='warranty',
            field=models.TextField(blank=True, help_text='Warranty information'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='raw_email_content',
            field=models.TextField(blank=True, help_text='Original email content from vendor'),
        ),
    ]
